development:
  adapter: postgresql
  database: hello_development
  encoding: utf8
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: hello_test
  encoding: utf8
  host: localhost
  pool: 5
  timeout: 5000

# Requried for rake assets:precompile in development. This is automatically overwritten at
# deploy-time by Heroku. See config/environments/development.rb.
#
production:
  adapter: postgresql
  database: hello_development
  encoding: utf8
  host: localhost
  pool: 5
  timeout: 5000

